name: Manual Disk Space Check

on:
  workflow_dispatch: # Enables manual trigger from the GitHub UI

jobs:
  check-runner-disk:
    runs-on: ubuntu-latest
    steps:
      - name: Show runner image version
        run: |
          echo "Current runner version: ${{ runner.version }}"
          cat /etc/os-release || true
          uname -a
          
      - name: Show disk space at job start
        run: df -h

      # Example command (replace this with your build/setup steps)
      - name: Example step
        run: echo "Do your build or setup here"

      - name: Show disk space at job end
        run: df -h
