name: TEST Branch Creation
on:
  workflow_dispatch:

jobs:
  working:
    runs-on: ubuntu-latest
    environment: publishing
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
       ref: main    
       token: ${{ secrets.PAT }}
    - name: Create New Branch
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        set -e
        # Configure git and Push updates
        git config --global user.email github-actions@github.com
        git config --global user.name github-actions
        branch=automated-update-for-image-history-$GITHUB_RUN_ID
        git checkout -b $branch
        git push origin $branch



